// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  products: [
    {
      id: 12,
      name: 'Aile de raie',
      category: 0,
      price: 10.0,
      unit: 'kg',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: 'Pêche à la corde',
      owner: 'tig',
      images: [
        'https://www.lacrieedacote.fr/wp-content/uploads/2021/03/Poissons-frais-Aile-de-Raie-Sauvage-pelee-webp-1.webp',
        'https://www.viviersdaudierne.com/wp-content/uploads/2019/05/f07427ef-dd4a-4962-bc38-3606c4839cc4.jpg',
      ],
    },
    {
      id: 9,
      name: 'Araignées',
      category: 2,
      price: 7.0,
      unit: 'kg',
      availability: false,
      sale: false,
      discount: 0.0,
      comments: 'Hors saison,  pêche aux casiers',
      owner: 'tig',
      images: [
        'https://www.comptoirdelamer.fr/wp-content/uploads/2020/07/araignee-de-mer2-istock.jpg',
      ],
    },
    {
      id: 3,
      name: 'Bar de ligne',
      category: 0,
      price: 30.0,
      unit: 'kg',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: 'Plus de 1.5kg le poisson',
      owner: 'tig',
      images: [
        'https://img.passeportsante.net/1200x675/2021-03-19/i100431-darne-de-saumon.webp',
      ],
    },
    {
      id: 2,
      name: 'Bar de ligne portion',
      category: 0,
      price: 10.0,
      unit: 'pièce',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: 'Environ 550-700g la pièce',
      owner: 'tig',
      images: [
        'https://img.passeportsante.net/1200x675/2021-03-19/i100431-darne-de-saumon.webp',
      ],
    },
    {
      id: 10,
      name: 'Bouquets cuits',
      category: 1,
      price: 8.0,
      unit: '100g',
      availability: false,
      sale: false,
      discount: 0.0,
      comments: "Hors saison, pêche à l'épuisette",
      owner: 'tig',
      images: ['https://media.cdnws.com/_i/113127/855/1506/58/105864348.jpeg'],
    },
    {
      id: 1,
      name: 'Filet Bar de ligne',
      category: 0,
      price: 7.0,
      unit: '2 filets',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: 'environ 300g',
      owner: 'tig',
      images: [
        'https://www.frais-livre.fr/1386-large_default/filet-de-bar-avec-peau-160180g-500-g.jpg',
      ],
    },
    {
      id: 5,
      name: 'Filet Julienne',
      category: 0,
      price: 19.0,
      unit: 'kg',
      availability: false,
      sale: false,
      discount: 0.0,
      comments: 'Pêche à la corde',
      owner: 'tig',
      images: [
        'https://www.lacrieedacote.fr/wp-content/uploads/2021/03/Poissons-frais-Aile-de-Raie-Sauvage-pelee-webp-1.webp',
        'https://www.viviersdaudierne.com/wp-content/uploads/2019/05/f07427ef-dd4a-4962-bc38-3606c4839cc4.jpg',
      ],
    },
    {
      id: 7,
      name: 'Huitres N°2 St Vaast',
      category: 1,
      price: 9.5,
      unit: 'Dz',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: '',
      owner: 'tig',
      images: ['https://media.cdnws.com/_i/113127/855/1506/58/105864348.jpeg'],
    },
    {
      id: 8,
      name: 'Huitres N°2 St Vaast',
      category: 1,
      price: 38.0,
      unit: '4 Dz',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: '',
      owner: 'tig',
      images: [
        'https://www.frais-livre.fr/1386-large_default/filet-de-bar-avec-peau-160180g-500-g.jpg',
      ],
    },
    {
      id: 13,
      name: 'Huîtres N°2 OR St Vaast',
      category: 1,
      price: 12.0,
      unit: 'Dz',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: "Médaille d'or Salon Agriculture",
      owner: 'tig',
      images:['https://www.lebateaudethibault.fr/cdn/shop/products/image_8f711dd1-696a-424c-8c51-12b2146f5f0a_1200x1200.jpg?v=1638115079']
    },
    {
      id: 14,
      name: 'Huîtres N°2 OR St Vaast',
      category: 1,
      price: 24.0,
      unit: '2 Dz',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: "Médaille d'or salon agriculture",
      owner: 'tig',
    },
    {
      id: 15,
      name: 'Huîtres N°2 OR St Vaast',
      category: 1,
      price: 48.0,
      unit: '4 Dz',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: "Médaille d'or salon agriculture",
      owner: 'tig',
    },
    {
      id: 16,
      name: 'Huîtres N°2 St Vaast',
      category: 1,
      price: 19.0,
      unit: '2 Dz',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: '',
      owner: 'tig',
    },
    {
      id: 4,
      name: 'Lieu jaune de ligne',
      category: 0,
      price: 12.0,
      unit: 'kg',
      availability: true,
      sale: false,
      discount: 0.0,
      comments: 'Environ 550-700g la portion',
      owner: 'tig',
    },
    {
      id: 6,
      name: 'Moules de pêche',
      category: 1,
      price: 7.0,
      unit: 'kg',
      availability: true,
      sale: true,
      discount: 5.0,
      comments: '',
      owner: 'tig',
    },
  ],
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
